### PR TITLE
Use stream tags instead of separate control stream

### PR DESCRIPTION
**Pull request by rubund**

### CODE REVIEW

**Comment by rubund** [comment]
This makes is more straightforward to "quickly" connect up a DAB flow graph in GRC with the basic building blocks.

**Comment by rubund** [comment]
@andrmuel  I know you have given me permission to merge, but this is quite an extensive "architectural" change, so I would prefer to have your approval.

**Comment by rubund** [comment]
but we can wait. seems to not be so stable as before (need to figure it out first)

**Comment by rubund** [comment]
found the issue and pushed a fix:  60ffea93962f1ea2cd6e09816ae12e670fc73bde

**Comment by andrmuel** [comment]
Hello Ruben

I have no experience with stream tags (they weren't around when I wrote the original code), so I'm afraid I can't help much in terms of technical expertise. However I'm happy to trust on your judgement, so I'll just go ahead and merge it :-)

Thanks again for all your work!

**Comment by rubund** [comment]
Perfect! Thanks.

> they weren't around when I wrote the original code

I knew that. That is why I was not afraid of insulting your original design choices by suggesting to change it :)

I tested the CPU utilisation with the old approach and the new approach (stream tags). I cannot see any noticeable difference. But at least the flow graphs in GRC look cleaner now. I will maybe put together an hierarchical GRC flow graph for the whole receiver (what is now in python blocks). It would make it easier for people to quickly grasp how a DAB receiver works.

**Comment by andrmuel** [comment]
Great! Please feel free to insult any of my design choices :-)

**Pull request merged**
